### PR TITLE
fix: restrict endorsement requests visibility to users own requests

### LINKED ISSUE #195: Filter endorsement requests by requester for regular users
### Issue Description  
Regular users are currently seeing all endorsement requests they’ve ever been involved with, rather than only the ones they created. This change will ensure non-superusers only ever see their own requests.  

Fixes #183 

### Severity/Priority

- [ ] Critical  
- [x] High  
- [ ] Medium  
- [ ] Low  

### Checklist

- [x] I have read and followed the project's code of conduct.  
- [x] I have searched for similar issues before creating this one.  
- [ ] I have provided all the necessary information to understand and reproduce the issue.  
- [x] I am willing to contribute to the resolution of this issue.

### PR DESCRIPTION
**Pull request by mbramani**
Date: 4 May 2025

Developer Name: @mbramani

---

## Issue Ticket Number

- Closes #195 

## Description

Fixed a privacy issue where users could see all endorsement requests in the system, not just those they were involved with. This PR ensures that regular users can only see endorsement requests they have participated in as an endorser.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
 <summary>Before fix - user could see all requests</summary>

### GET /skills/request
image

```js
{
    "requests": [
        {
            "skillId": 1,
            "skillName": "Java Programming",
            "endorseId": "u7TlhKZdq63zLaJb0GIQ",
            "status": "PENDING",
            "endorsements": [
                {
                    "id": 1,
                    "endorserId": "a5QSIMHVithZaKpEA8oC",
                    "endorsementDate": "2025-05-04T06:20:11.340996Z",
                    "message": "Excellent Java skills and team contribution."
                },
                {
                    "id": 4,
                    "endorserId": "jY6WlBFDA35HBhErWFM7",
                    "endorsementDate": "2025-05-04T09:25:12Z",
                    "message": "So much good at java"
                }
            ]
        },
        {
            "skillId": 1,
            "skillName": "Java Programming",
            "endorseId": "jY6WlBFDA35HBhErWFM7",
            "status": "APPROVED",
            "endorsements": [
                {
                    "id": 3,
                    "endorserId": "a5QSIMHVithZaKpEA8oC",
                    "endorsementDate": "2025-05-04T08:25:12Z",
                    "message": "Good at java"
                }
            ]
        },
        {
            "skillId": 3,
            "skillName": "Data Structures",
            "endorseId": "jY6WlBFDA35HBhErWFM7",
            "status": "PENDING",
            "endorsements": [
                {
                    "id": 5,
                    "endorserId": "u7TlhKZdq63zLaJb0GIQ",
                    "endorsementDate": "2025-05-04T10:25:12Z",
                    "message": "good at at dsa"
                }
            ]
        }
    ],
    "users": [
        {
            "id": "u7TlhKZdq63zLaJb0GIQ",
            "name": "Ruhi Sui"
        },
        {
            "id": "jY6WlBFDA35HBhErWFM7",
            "name": "Manoj Chope"
        },
        {
            "id": "a5QSIMHVithZaKpEA8oC",
            "name": "mohit ramani"
        }
    ]
}
```

### GET /skills/request?status=PENDING
image
```js
{
    "requests": [
        {
            "skillId": 1,
            "skillName": "Java Programming",
            "endorseId": "u7TlhKZdq63zLaJb0GIQ",
            "status": "PENDING",
            "endorsements": [
                {
                    "id": 1,
                    "endorserId": "a5QSIMHVithZaKpEA8oC",
                    "endorsementDate": "2025-05-04T06:20:11.340996Z",
                    "message": "Excellent Java skills and team contribution."
                },
                {
                    "id": 4,
                    "endorserId": "jY6WlBFDA35HBhErWFM7",
                    "endorsementDate": "2025-05-04T09:25:12Z",
                    "message": "So much good at java"
                }
            ]
        },
        {
            "skillId": 3,
            "skillName": "Data Structures",
            "endorseId": "jY6WlBFDA35HBhErWFM7",
            "status": "PENDING",
            "endorsements": [
                {
                    "id": 5,
                    "endorserId": "u7TlhKZdq63zLaJb0GIQ",
                    "endorsementDate": "2025-05-04T10:25:12Z",
                    "message": "good at at dsa"
                }
            ]
        }
    ],
    "users": [
        {
            "id": "u7TlhKZdq63zLaJb0GIQ",
            "name": "Ruhi Sui"
        },
        {
            "id": "jY6WlBFDA35HBhErWFM7",
            "name": "Manoj Chope"
        },
        {
            "id": "a5QSIMHVithZaKpEA8oC",
            "name": "mohit ramani"
        }
    ]
}
```

</details>

<details>
<summary>After fix - user only sees their endorsed requests</summary>

 ### GET /skills/request?dev=true

image

 ```js
 {
    "requests": [
        {
            "skillId": 1,
            "skillName": "Java Programming",
            "endorseId": "u7TlhKZdq63zLaJb0GIQ",
            "status": "PENDING",
            "endorsements": [
                {
                    "id": 1,
                    "endorserId": "a5QSIMHVithZaKpEA8oC",
                    "endorsementDate": "2025-05-04T06:20:11.340996Z",
                    "message": "Excellent Java skills and team contribution."
                },
                {
                    "id": 4,
                    "endorserId": "jY6WlBFDA35HBhErWFM7",
                    "endorsementDate": "2025-05-04T09:25:12Z",
                    "message": "So much good at java"
                }
            ]
        },
        {
            "skillId": 1,
            "skillName": "Java Programming",
            "endorseId": "jY6WlBFDA35HBhErWFM7",
            "status": "APPROVED",
            "endorsements": [
                {
                    "id": 3,
                    "endorserId": "a5QSIMHVithZaKpEA8oC",
                    "endorsementDate": "2025-05-04T08:25:12Z",
                    "message": "Good at java"
                }
            ]
        }
    ],
    "users": [
        {
            "id": "u7TlhKZdq63zLaJb0GIQ",
            "name": "Ruhi Sui"
        },
        {
            "id": "jY6WlBFDA35HBhErWFM7",
            "name": "Manoj Chope"
        },
        {
            "id": "a5QSIMHVithZaKpEA8oC",
            "name": "mohit ramani"
        }
    ]
}
 ```

 ### GET /skills/request?status=PENDING&dev=true

image

  ```js
  {
    "requests": [
        {
            "skillId": 1,
            "skillName": "Java Programming",
            "endorseId": "u7TlhKZdq63zLaJb0GIQ",
            "status": "PENDING",
            "endorsements": [
                {
                    "id": 1,
                    "endorserId": "a5QSIMHVithZaKpEA8oC",
                    "endorsementDate": "2025-05-04T06:20:11.340996Z",
                    "message": "Excellent Java skills and team contribution."
                },
                {
                    "id": 4,
                    "endorserId": "jY6WlBFDA35HBhErWFM7",
                    "endorsementDate": "2025-05-04T09:25:12Z",
                    "message": "So much good at java"
                }
            ]
        }
    ],
    "users": [
        {
            "id": "u7TlhKZdq63zLaJb0GIQ",
            "name": "Ruhi Sui"
        },
        {
            "id": "jY6WlBFDA35HBhErWFM7",
            "name": "Manoj Chope"
        },
        {
            "id": "a5QSIMHVithZaKpEA8oC",
            "name": "mohit ramani"
        }
    ]
}
 ```
 </details>
 
<details>
  <summary>Video showing the bug before and after it was fixed</summary>
  

https://github.com/user-attachments/assets/b9ba148d-c138-4b1f-9ca8-031e18708425

</details>

## Test Coverage
<details>
<summary>Integration test results</summary>

### Skill Request Integration Test

image

### Integration Tests Result
image

### Unit Test Results
image

### Test Coverage
image

</details>

### CODE REVIEW

**Comment by MayankBansal12** [comment]
@mbramani Please put this bug fix under feature flag

**Comment by mbramani** [comment]
> @mbramani Please put this bug fix under feature flag

Added the feature flag for the bug fix

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 1]
```diff
@@ -128,40 +156,50 @@ public GenericResponse<String> approveRejectSkillRequest(
...
-                                                if (!userDetails.containsKey(endorserId)) {
+                                                if (!userViewModelMap.containsKey(endorserId)) {
                                                     RdsGetUserDetailsResDto endorserRdsDetails =
                                                             rdsService.getUserDetails(endorserId);
                                                     UserViewModel endorserDetails =
                                                             getUserModalFromRdsDetails(endorserId, endorserRdsDetails);
-                                                    userDetails.put(endorserId, endorserDetails);
+                                                    userViewModelMap.put(endorserId, endorserDetails);
                                                 }
                                             });
```
Comment (Shyam-Vishwakarma) [inline skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java:204]: If in `devMode` and `currentUser` is not a `super-user` then, is it true that endorsements will have `currentUser as endorser` always? 
 If yes, can we avoid this redundant looping over all endorsements for this specific case?
 
You can see that for this case; endorsements are retrieved as `endorsements =
                                                endorsementRepository.findByEndorseIdAndSkillIdAndEndorserId(
                                                        endorseId, skillId, currentUserId);`.

File: skill-tree/src/test/java/utils/CustomResultMatchers.java [hunk 2]
```diff
@@ -67,6 +67,61 @@ public static ResultMatcher hasUser(String userId, String name) {
...
+            // Find the request for the given skillName and endorseId
+            JsonNode matchingRequest = findBySkillAndEndorseId(requests, skillName, endorseId);
+
+            // Assert that the request is null
+            assertThat(matchingRequest).isNull();
+        };
+    }
+
+    public static ResultMatcher doesNotHaveEndorsement(
+            String skillName, String endorseId, String endorserId) {
```
Comment (Shyam-Vishwakarma) [inline skill-tree/src/test/java/utils/CustomResultMatchers.java:91]: I did not see any usage of this method. Why did you add this?

File: skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java [hunk 3]
```diff
@@ -220,6 +220,60 @@ public void getAllRequests_ByStatus_ShouldReturnFilteredRequests() throws Except
...
+            throws Exception {
+        mockMvc
+                .perform(
+                        MockMvcRequestBuilders.get(route + "?status=APPROVED&dev=true")
+                                .contentType(MediaType.APPLICATION_JSON))
+                .andExpect(MockMvcResultMatchers.status().is(200))
+                .andExpect(CustomResultMatchers.hasSkillRequest("Springboot", "user-id", "APPROVED"))
+                .andExpect(CustomResultMatchers.doesNotHaveSkillRequest("Java", "user-id"))
+                .andExpect(CustomResultMatchers.doesNotHaveSkillRequest("Springboot", "user-id-2"));
+    }
```
Comment (Shyam-Vishwakarma) [inline skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java:257]: - Endorsements are being filtered by `Approved` status but there is only one mock endorsement where `user-id-2` is endorser having status as `Approved`. Please add some mock endorsements having status other than `Approved` to verify filtering works correctly.

- Also, check whether response contains endorsements or not using `hasEndorsement()` method.

File: skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java [hunk 4]
```diff
@@ -220,6 +220,60 @@ public void getAllRequests_ByStatus_ShouldReturnFilteredRequests() throws Except
                 .andExpect(CustomResultMatchers.hasUser("user-id-2", " "));
     }
 
+    @Test
+    @DisplayName("Normal user with dev flag - should only see endorsed requests")
+    @WithCustomMockUser(
```
Comment (Shyam-Vishwakarma) [inline skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java:225]: - Test names could be written more clearly e.g. Normal user with dev flag - should only see requests where user is endorser (fix others also if required)

- Please add a check that there are no endorsements which has endorser other than this user

File: skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java [hunk 5]
```diff
@@ -220,6 +220,60 @@ public void getAllRequests_ByStatus_ShouldReturnFilteredRequests() throws Except
...
+                .andExpect(CustomResultMatchers.doesNotHaveSkillRequest("Springboot", "user-id-2"));
+    }
+
+    @Test
+    @DisplayName(
+            "Normal user filtering by status without dev flag - should see all requests with status (original behavior)")
+    @WithCustomMockUser(
+            username = "user-id-2",
+            authorities = {"USER"})
+    public void getRequestsByStatus_withoutDevFlag_shouldShowAllRequestsWithStatus()
```
Comment (Shyam-Vishwakarma) [inline skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java:265]: - Endorsements are being filtered by `Approved` status but there is only one mock endorsement where `user-id-2` is endorser having status as `Approved`. Please add some mock endorsements having status other than `Approved` to verify filtering works correctly.

- Also, check whether response contains endorsements or not using `hasEndorsement()` method.

**Review by Shyam-Vishwakarma — CHANGES_REQUESTED** [review]

File: skill-tree/src/test/java/utils/CustomResultMatchers.java
Comment (MayankBansal12) [inline skill-tree/src/test/java/utils/CustomResultMatchers.java:1]: are the comments added in this file, necessary? if not, please remove them!

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 6]
```diff
@@ -67,25 +67,53 @@ public SkillRequestsDto getAllRequests() {
...
+
+        if (!devMode) {
+            skillRequests = userSkillRepository.findByStatus(status);
+        } else if (userRole.isSuper_user()) {
+            // New behavior for superuser
+            skillRequests = userSkillRepository.findByStatus(status);
+        } else {
+            // New behavior for normal user
+            skillRequests = userSkillRepository.findByStatusAndEndorserId(status, userId);
+        }
```
Comment (MayankBansal12) [inline skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java:108]: what are we trying to achieve here? what's the new behaviour for super user and normal user and what was before dev flag?

File: skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java [hunk 7]
```diff
@@ -16,5 +16,18 @@ public interface UserSkillRepository extends JpaRepository<UserSkills, Integer>
             "SELECT us FROM UserSkills us "
                     + "JOIN Endorsement e ON us.userId = e.endorseId "
                     + "WHERE e.endorserId = :endorserId")
+    List<UserSkills> findUserSkillsByEndorserIdLegacy(@Param("endorserId") String endorserId);
+
+    @Query(
+            "SELECT us FROM UserSkills us "
+                    + "JOIN Endorsement e ON us.userId = e.endorseId AND us.skill.id = e.skill.id "
+                    + "WHERE e.endorserId = :endorserId")
```
Comment (MayankBansal12) [inline skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java:24]: where is the old query? why are we making a change in the legacy/previous query?

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 8]
```diff
@@ -128,40 +156,50 @@ public GenericResponse<String> approveRejectSkillRequest(
...
+
+                                    if (!devMode) {
+                                        endorsements =
+                                                endorsementRepository.findByEndorseIdAndSkillId(endorseId, skillId);
+                                    } else if (isSuperUser) {
+                                        endorsements =
+                                                endorsementRepository.findByEndorseIdAndSkillId(endorseId, skillId);
+                                    } else {
+                                        endorsements =
+                                                endorsementRepository.findByEndorseIdAndSkillIdAndEndorserId(
```
Comment (MayankBansal12) [inline skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java:181]: if `devMode` is off, both super and normal user will see the same requests but with `dev` flag, normal user will view their requests and super users will view all requests, is that the behaviour?

**Comment by MayankBansal12** [comment]
Hey @mbramani, I would suggest adding a screen recording to show the behaviour in the frontend with dev mode on, this will help reviewers verify that the bug faced has been resolved with your PR.

File: skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java (hunk 7 above)
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java:24]: We're keeping the old method as "Legacy" to support the feature flag implementation (dev=true), allowing for controlled rollout of this privacy fix.

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java (hunk 6 above)
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java]: Before this fix, we had a significant privacy issue:

Original Behavior (without dev flag)
Super Users: Could see all skill requests by status (correct behavior)
Normal Users: Could also see all requests by status (privacy vulnerability)
For example, a regular user could see ALL pending requests in the system by querying ?status=PENDING, whether they were involved with them or not.

New Behavior (with dev flag)
Super Users: No change - they still see all skill requests by status
Normal Users: Only see skill requests they've personally endorsed with the specified status

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java (hunk 8 above)
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java]: You're almost correct, but there's a nuance in the behavior when devMode is OFF:

1. With devMode OFF:
- Super users: See ALL requests in the system
- Normal users: See requests they've endorsed, but with a privacy bug that shows ALL skills from a user once they've endorsed ANY skill for that user

2. With devMode ON:
- Super users: Still see ALL requests (unchanged)
- Normal users: See ONLY the specific user+skill combinations they've personally endorsed

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java (hunk 1 above)
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java:197]: Optimized user details retrieval for currentUser in devMode as suggested.

File: skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java (hunk 4 above)
Comment (mbramani) [reply skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java]: this [commit](https://github.com/Real-Dev-Squad/skill-tree-backend/pull/196/commits/b88f7db36a7e078f4b7c4f23da3f90281b5e6bc0) will resolve it

File: skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java (hunk 5 above)
Comment (mbramani) [reply skill-tree/src/test/java/com/RDS/skilltree/integration/skills/GetAllSkillRequestIntegrationTest.java]: this [commit](https://github.com/Real-Dev-Squad/skill-tree-backend/pull/196/commits/b88f7db36a7e078f4b7c4f23da3f90281b5e6bc0) will resolve it

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 9]
```diff
@@ -128,40 +152,56 @@ public GenericResponse<String> approveRejectSkillRequest(
...
+                                                        endorseId, skillId, currentUserId);
+
+                                        // Optimization: We already know the currentUserId will be in this list,
+                                        // so we can ensure it's in the map before the forEach loop
+                                        if (!userViewModelMap.containsKey(currentUserId)) {
+                                            RdsGetUserDetailsResDto currentUserDetails =
+                                                    rdsService.getUserDetails(currentUserId);
+                                            UserViewModel currentUserViewModel =
+                                                    getUserModalFromRdsDetails(currentUserId, currentUserDetails);
+                                            userViewModelMap.put(currentUserId, currentUserViewModel);
```
[the remark this answers is not in the document]
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java]: This is resolved by this [commit](https://github.com/Real-Dev-Squad/skill-tree-backend/pull/196/commits/c02edc8c2f184ccf03b5858f36664eac2834cbba)

**Review by Shyam-Vishwakarma — APPROVED** [review]
Looks good to me.

File: skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java (hunk 7 above)
Comment (MayankBansal12) [reply skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java:24]: What was being used before, since I see this legacy query being introduced here?

Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java:24]: Legacy was used here before 
For example findUserSkillsByEndorserIdLegacy(@Param("endorserId")
Was before findUserSkillsByEndorserId(@Param("endorserId")

**Review by MayankBansal12 — DISMISSED** [review]

**Comment by Shyam-Vishwakarma** [comment]
@mbramani there was an issue (#183) already opened regarding this, why did you create a new one (#195)?

**Comment by mbramani** [comment]
It was about discovery not the fix

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 10]
```diff
@@ -129,49 +151,50 @@ public GenericResponse<String> approveRejectSkillRequest(
...
 
-                                    if (!userDetails.containsKey(endorseId)) {
-                                        RdsGetUserDetailsResDto endorseRdsDetails =
-                                                rdsService.getUserDetails(endorseId);
-                                        UserViewModel endorseDetails =
-                                                getUserModalFromRdsDetails(endorseId, endorseRdsDetails);
-                                        userDetails.put(endorseId, endorseDetails);
-                                    }
+                                    endorsements =
+                                            endorsementRepository.findByEndorseIdAndSkillId(endorseId, skillId);
```
[the remark this answers is not in the document]
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java]: Done

**Review by MayankBansal12 — APPROVED** [review]

**Review by MayankBansal12 — APPROVED** [review]

File: skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java [hunk 11]
```diff
@@ -16,5 +16,18 @@ public interface UserSkillRepository extends JpaRepository<UserSkills, Integer>
             "SELECT us FROM UserSkills us "
                     + "JOIN Endorsement e ON us.userId = e.endorseId "
                     + "WHERE e.endorserId = :endorserId")
+    List<UserSkills> findUserSkillsByEndorserIdLegacy(@Param("endorserId") String endorserId);
+
+    @Query(
+            "SELECT us FROM UserSkills us "
+                    + "JOIN Endorsement e ON us.userId = e.endorseId AND us.skill.id = e.skill.id "
```
Comment (iamitprakash) [inline skill-tree/src/main/java/com/RDS/skilltree/repositories/UserSkillRepository.java:23]: fix string concatenation please

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillService.java [hunk 12]
```diff
@@ -12,9 +12,9 @@ public interface SkillService {
 
     SkillViewModel create(CreateSkillViewModel skill);
 
-    SkillRequestsDto getAllRequests();
+    SkillRequestsDto getAllRequests(boolean devMode);
```
Comment (iamitprakash) [inline skill-tree/src/main/java/com/RDS/skilltree/services/SkillService.java:15]: please change this devMode variable name

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 13]
```diff
@@ -67,7 +67,11 @@ public SkillRequestsDto getAllRequests() {
         if (userRole.isSuper_user()) {
             skillRequests = userSkillRepository.findAll();
         } else {
-            skillRequests = userSkillRepository.findUserSkillsByEndorserId(userId);
+            if (devMode) {
+                skillRequests = userSkillRepository.findUserSkillsByEndorserId(userId);
```
Comment (iamitprakash) [inline skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java:71]: flat this nesting loop

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java [hunk 14]
```diff
@@ -82,8 +86,26 @@ public SkillRequestsDto getAllRequests() {
...
-        List<UserSkills> skillRequests = userSkillRepository.findByStatus(status);
+    public SkillRequestsDto getRequestsByStatus(UserSkillStatusEnum status, boolean devMode) {
+        JwtUser jwtDetails =
+                (JwtUser) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
+
+        RdsGetUserDetailsResDto userDetails = rdsService.getUserDetails(jwtDetails.getRdsUserId());
+        RdsUserViewModel.Roles userRole = userDetails.getUser().getRoles();
+        String userId = userDetails.getUser().getId();
+
+        List<UserSkills> skillRequests;
```
Comment (iamitprakash) [inline skill-tree/src/main/java/com/RDS/skilltree/services/SkillServiceImplementation.java:97]: as discussed please let me know , what below code is doing

**Review by iamitprakash — CHANGES_REQUESTED** [review]

**Comment by Shyam-Vishwakarma** [comment]
hello @mbramani 
can you please verify whether this test is passing?

This is what we are expecting:
If user A has added endorsement for a user B on a particular skill, and some other users have also added endorsements for the same user. Then user A should see his own endorsements along with the other's endorsements also.

```Java
private Skill createAndSaveSkill(String skillName) {
    Skill skill = new Skill();
    skill.setName(skillName);
    skill.setType(SkillTypeEnum.ATOMIC);
    skill.setCreatedBy("super-user-id");
    return skillRepository.save(skill);
}

private UserSkills createAndSaveUserSkills(Skill skill, String userId, UserSkillStatusEnum status) {
    UserSkills userSkills = new UserSkills();
    userSkills.setSkill(skill);
    userSkills.setUserId(userId);
    userSkills.setStatus(status);
    return userSkillRepository.save(userSkills);
}

private Endorsement createAndSaveEndorsement(int id, String endorseId, String endorserId, Skill skill, String message) {
    Endorsement endorsement = new Endorsement();
    endorsement.setId(id);
    endorsement.setEndorseId(endorseId);
    endorsement.setEndorserId(endorserId);
    endorsement.setSkill(skill);
    endorsement.setMessage(message);
    return endorsementRepository.save(endorsement);
}

    @Test
    @DisplayName("User should see other user's endorsements also, where current user is involved")
    @WithCustomMockUser(username = "user-id-2", authorities = {"USER"})
    public void getAllRequests_ShouldReturn_EndorsementsOfOtherUsersInvolved() throws Exception {
        skillRepository.deleteAll();
        userSkillRepository.deleteAll();
        endorsementRepository.deleteAll();

        Skill skill = createAndSaveSkill("Java");

        createAndSaveUserSkills(skill, "user-id", UserSkillStatusEnum.PENDING);

        createAndSaveEndorsement(1, "user-id", "super-user-id", skill, "message 1");
        createAndSaveEndorsement(2, "user-id", "user-id-2", skill, "message 2");

        mockMvc.perform(MockMvcRequestBuilders.get(route + "?dev=true")
                        .contentType(MediaType.APPLICATION_JSON))
                .andExpect(MockMvcResultMatchers.status().is(200))
                .andExpect(CustomResultMatchers.hasSkillRequest("Java", "user-id", "PENDING"))
                .andExpect(CustomResultMatchers.hasEndorsement("Java", "user-id", "super-user-id", "message 1"))
                .andExpect(CustomResultMatchers.hasEndorsement("Java", "user-id", "user-id-2", "message 2"));
    }
```

Additionally, can you please come up with a case for which, users can see the endorsements for a skill request in which they are not involved as an endorser?

File: skill-tree/src/main/java/com/RDS/skilltree/repositories/EndorsementRepository.java [hunk 15]
```diff
@@ -8,4 +8,7 @@ public interface EndorsementRepository extends JpaRepository<Endorsement, Intege
     List<Endorsement> findBySkillId(Integer skillId);
 
     List<Endorsement> findByEndorseIdAndSkillId(String endorseId, Integer skillId);
+
+    List<Endorsement> findByEndorseIdAndSkillIdAndEndorserId(
```
Comment (surajmaity1) [inline skill-tree/src/main/java/com/RDS/skilltree/repositories/EndorsementRepository.java:12]: Hi @mbramani ,
I couldn't find any references to the `findByEndorseIdAndSkillIdAndEndorserId `function being used in the codebase. Could you please clarify where and how this function is being utilized?

Thank you!

Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/repositories/EndorsementRepository.java]: Thank you for addressing this, removed it.

File: skill-tree/src/main/java/com/RDS/skilltree/services/SkillService.java (hunk 12 above)
Comment (mbramani) [reply skill-tree/src/main/java/com/RDS/skilltree/services/SkillService.java]: For the reference i go through the our website backend and found there we are using isDev and dev as feature flag

**Review by iamitprakash — CHANGES_REQUESTED** [review]
please add SS of -ve test with valid user ID

File: skill-tree/src/test/java/utils/CustomResultMatchers.java [hunk 16]
```diff
@@ -67,6 +67,26 @@ public static ResultMatcher hasUser(String userId, String name) {
         };
     }
 
+    public static ResultMatcher doesNotHaveSkillRequest(String skillName, String endorseId) {
```
Comment (iamitprakash) [inline skill-tree/src/test/java/utils/CustomResultMatchers.java:70]:
```
public static ResultMatcher doesNotHaveSkillRequest(String skillName, String endorseId) {
    return result -> {
        String json = result.getResponse().getContentAsString();
        ObjectMapper objectMapper = new ObjectMapper();
        JsonNode root = objectMapper.readTree(json);

        JsonNode requests = root.get("requests");
        if (requests == null || !requests.isArray() || requests.size() == 0) {
            // No requests means the skill request definitely does not exist
            return;
        }

        JsonNode matchingRequest = findBySkillAndEndorseId(requests, skillName, endorseId);
        assertThat(matchingRequest).isNull();  
    };
}
```

**Review by iamitprakash — APPROVED** [review]
